### ISSUE TITLE
Image View Page

### ISSUE THREAD

**Issue by gagichce** [macGRID-SRN/hitchBOT#77]
Same as the page before, but nicer looking with the new formatting

**Comment by jamiecounsell** [comment]
@gagichce, can you send me the file you had previously? I can use the function to create the new page faster. Styling isn't a problem, but I'm still slow on the ASP stuff.

**Comment by gagichce** [comment]
@jamiecounsell https://github.com/macGRID-SRN/hitchBOT/blob/67031eef7e7eb5e2fc4ec83bd9d7bcd4d541880b/server/hitchbotAPI/hitchbotAPI/ApproveImagesPages/ViewImages.aspx.cs
